# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Dec  1 05:22:16 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 588)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/images/animes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.avaLabel = QtGui.QLabel(self.centralwidget)
        self.avaLabel.setObjectName("avaLabel")
        self.horizontalLayout_2.addWidget(self.avaLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.anime_list_widget = QtGui.QListWidget(self.centralwidget)
        self.anime_list_widget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.anime_list_widget.setProperty("isWrapping", True)
        self.anime_list_widget.setWordWrap(True)
        self.anime_list_widget.setObjectName("anime_list_widget")
        self.horizontalLayout_8.addWidget(self.anime_list_widget)
        self.image_label = QtGui.QLabel(self.centralwidget)
        self.image_label.setMaximumSize(QtCore.QSize(185, 245))
        self.image_label.setBaseSize(QtCore.QSize(0, 0))
        self.image_label.setText("")
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout_8.addWidget(self.image_label)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.label_sinopse = QtGui.QLabel(self.centralwidget)
        self.label_sinopse.setWordWrap(True)
        self.label_sinopse.setObjectName("label_sinopse")
        self.verticalLayout.addWidget(self.label_sinopse)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchEdit = QtGui.QLineEdit(self.centralwidget)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout.addWidget(self.searchEdit)
        self.show_button = QtGui.QPushButton(self.centralwidget)
        self.show_button.setObjectName("show_button")
        self.horizontalLayout.addWidget(self.show_button)
        self.labelSearch = QtGui.QLabel(self.centralwidget)
        self.labelSearch.setAutoFillBackground(False)
        self.labelSearch.setText("")
        self.labelSearch.setObjectName("labelSearch")
        self.horizontalLayout.addWidget(self.labelSearch)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.res_list_widget = QtGui.QListWidget(self.centralwidget)
        self.res_list_widget.setWordWrap(False)
        self.res_list_widget.setObjectName("res_list_widget")
        self.horizontalLayout_6.addWidget(self.res_list_widget)
        self.options_list_widget = QtGui.QListWidget(self.centralwidget)
        self.options_list_widget.setObjectName("options_list_widget")
        self.horizontalLayout_6.addWidget(self.options_list_widget)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.loading_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(18)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.loading_label.setFont(font)
        self.loading_label.setTextFormat(QtCore.Qt.AutoText)
        self.loading_label.setObjectName("loading_label")
        self.horizontalLayout_5.addWidget(self.loading_label)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.download_button = QtGui.QPushButton(self.centralwidget)
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_5.addWidget(self.download_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 19))
        self.menubar.setObjectName("menubar")
        self.menu_About = QtGui.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_About_Semard = QtGui.QAction(MainWindow)
        self.action_About_Semard.setObjectName("action_About_Semard")
        self.menu_About.addAction(self.action_About_Semard)
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.anime_list_widget, self.searchEdit)
        MainWindow.setTabOrder(self.searchEdit, self.show_button)
        MainWindow.setTabOrder(self.show_button, self.res_list_widget)
        MainWindow.setTabOrder(self.res_list_widget, self.options_list_widget)
        MainWindow.setTabOrder(self.options_list_widget, self.download_button)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Semard - Anime Version", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Lista de animes:", None, QtGui.QApplication.UnicodeUTF8))
        self.avaLabel.setText(QtGui.QApplication.translate("MainWindow", "disponíveis.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sinopse.setText(QtGui.QApplication.translate("MainWindow", "Sinopse:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Procurar:", None, QtGui.QApplication.UnicodeUTF8))
        self.show_button.setText(QtGui.QApplication.translate("MainWindow", "&Show Episodes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Episódios", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Links para download:", None, QtGui.QApplication.UnicodeUTF8))
        self.loading_label.setText(QtGui.QApplication.translate("MainWindow", "Carregando...", None, QtGui.QApplication.UnicodeUTF8))
        self.download_button.setText(QtGui.QApplication.translate("MainWindow", "&Abrir Link", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_About.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About_Semard.setText(QtGui.QApplication.translate("MainWindow", "&About Semard", None, QtGui.QApplication.UnicodeUTF8))

